// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: yinyin

#ifndef _YINYIN_UI_H
#define _YINYIN_UI_H

//#define LV_RADIUS_CIRCLE_YINYIN 99

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t* ui_Screen1;
extern lv_obj_t* ui_Panel1;
extern lv_obj_t* ui_Dropdown1;
extern lv_obj_t* ui_Label1;
extern lv_obj_t* ui____initial_actions0;




void ui_init(void);
void ui_update();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
